import 'app/globals.scss'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {ReactNode} from "react";
import {Header} from "@/component/layout/header/header";
import Image from "next/image";
import abstraction from '@/assest/icon/abstraction.png'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: ReactNode
}) {
    return (
        <html lang="en">
        <body className={`${inter.className}`}>
        <div>
            <Header/>
            {children}
        </div>
        </body>
        </html>
    )
}
